name: Continuous Integration

on:
  push:
    branches: [main]
    tags:
  pull_request:

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        include:
        # linux
        - os: ubuntu-latest
          python: '3.10'
          toxenv: py
        - os: ubuntu-latest
          python: '3.11'
          toxenv: py
        - os: ubuntu-latest
          python: '3.12'
          toxenv: py
        - os: ubuntu-latest
          python: '3.13'
          toxenv: py
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - run: python -mpip install --upgrade setuptools pip tox virtualenv
    - run: tox -e ${{ matrix.toxenv }}
